language: cpp
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      - kalakris-cmake
    packages:
      - gcc-7
      - g++-7
      - cmake
env: 
compiler: gcc
install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
script:
  - cmake .
  - make
